---
title: 'ID Modeling Final Project: Cholera'
author: "Alicia Yang (ay2452), Ashley Tseng (at3346), Cassandra Coulter (cc4347), and Christopher Armbruster (cwa2118)"
date: "Due: May 6, 2020"
output: html_document
---

```{r setup, include = FALSE}
## Setting up file
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(deSolve)
```


```{r SIRW_model}
## Building SIRW model from Tuite et al. 2011
SIRW = function(t,state,parameters){
  with(as.list(c(state,parameters)),{
    
    lambda = (Beta_i*I + Beta_w*W)/N # force of infection
    
    dS = (-lambda*S*(1-Pw/100)); # susceptible compartment with probability of provision of clean water incorporated
    dI = (-gamma*I) + (lambda*S); # infectious compartment
    dR = (gamma*I); # recovered compartment
    dW = (xi*(I-W)); # environmental (bacterial) compartment normalized by total population size
    dcumI = (lambda*S)*(1-Pw/100);
    
    list(c(dS,dI,dR,dW,dcumI))
  })
}

## Specify initial conditions/parameters
times_SIRW = seq(0, 100, by = 1);  # run for 100 days
N = 9798046; # total population size in 2009
W0 = 0.0003; # initial concentration of bacteria (estimated from Hood et al. 1981)
I0 = 10; # initial no. of infectious individuals - set an arbitrary number of 10 for now
S0 = N - I0; # initial no. of Susceptible people
R0 = 0; # initial no. of Recovered people
Beta_i = 0.010; # transmission rate from case (Tuite et al. 2011, Appendix Table 2)
Beta_w = 0.944; # transmissibility of water (Tuite et al. 2011, Appendix Table 2)
gamma = 1/2.913; # mean duration of infectiousness (days) (Tuite et al. 2011, Appendix Table 2)
xi = 1/5.910; # mean survival of pathogen in water (weeks) (Tuite et al. 2011, Appendix Table 2)
Pw = 50; # probability of provision of clean water
state_SIRW = c(S = S0, I = I0, R = R0, W = W0, cumI = I0)
parameters_SIRW = c(gamma = gamma, xi = xi, Beta_i = Beta_i, Beta_w = Beta_w, Pw = Pw)
sim_SIRW = ode(y = state_SIRW, times = times_SIRW, func = SIRW, parms = parameters_SIRW)

View(sim_SIRW)

sim_haiti = as.data.frame(sim_SIRW)
sim_haiti %>% 
  ggplot(aes(x = time, y = cumI)) +
  geom_point() +
  labs(x = "Time (Days)", y = "Cumulative Incidence") +
  ggtitle("Haiti Cholera Outbreak, October-November 2010")

sim_haiti %>% 
  knitr::kable(digits = 3)
```


Apply the Haiti SIRW model to Nigeria cholera outbreak: 
```{r nigeria_outbreak}
## Read in Table 3 of Elimian et al. 2019 containing population size, no. of cholera cases, no. of cholera deaths, attack rate/100,000 population, and the case fatality rate (%) by state. The total country-wide estimates are in the last row of the dataset.
nigeria_data = 
  read_csv("./data/Nigeria_Cholera_Outbreak.csv", col_names = TRUE) %>%
  janitor::clean_names()


##### Northeast Nigeria region only: Adamawa, Bauchi, Borno, Gombe, Yobe #####
## Apply Haiti SIRW model to Nigeria cholera outbreak:
SIRW = function(t,state,parameters){
  with(as.list(c(state,parameters)),{
    
    lambda = (Beta_i*I + Beta_w*W)/N # force of infection
    
    dS = (-lambda*S*(1-Pw/100)); # susceptible compartment with probability of provision of clean water incorporated
    dI = (-gamma*I) + (lambda*S); # infectious compartment
    dR = (gamma*I); # recovered compartment
    dW = (xi*(I-W)); # environmental (bacterial) compartment normalized by total population size
    dcumI = (lambda*S)*(1-Pw/100);
    
    list(c(dS,dI,dR,dW,dcumI))
  })
}

## Specify initial conditions/parameters
times_SIRW_Nigeria = seq(0, 11*30, by = 1);  # run for 11 months
N = 24593161; # projected 2018 total population size of Nigeria's northeast states
W0 = 0.0003; # initial concentration of bacteria (estimated from Hood et al. 1981)
I0 = 10; # initial no. of infectious individuals - set an arbitrary number of 10 for now
S0 = N - I0; # initial no. of Susceptible people
R0 = 0; # initial no. of Recovered people
Beta_i = 0.010; # transmission rate from case (Tuite et al. 2011, Appendix Table 2)
Beta_w = 0.944; # transmissibility of water (Tuite et al. 2011, Appendix Table 2)
gamma = 1/2.913; # mean duration of infectiousness (days) (Tuite et al. 2011, Appendix Table 2)
xi = 1/5.910; # mean survival of pathogen in water (weeks) (Tuite et al. 2011, Appendix Table 2)
Pw = 50; # probability of provision of clean water
state_SIRW_Nigeria = c(S = S0, I = I0, R = R0, W = W0, cumI = I0)
parameters_SIRW_Nigeria = c(gamma = gamma, xi = xi, Beta_i = Beta_i, Beta_w = Beta_w)
sim_SIRW_Nigeria = ode(y = state_SIRW_Nigeria, times = times_SIRW_Nigeria, func = SIRW, parms = parameters_SIRW_Nigeria)

View(sim_SIRW_Nigeria)

sim_nigeria = as.data.frame(sim_SIRW_Nigeria)
sim_nigeria %>% 
  ggplot(aes(x = time, y = cumI)) +
  geom_point() +
  xlim(0, 11*30) +
  labs(x = "Time (Days)", y = "Cumulative Incidence") +
  ggtitle("Nigeria Cholera Outbreak, January-November 2018")

sim_nigeria %>% 
  knitr::kable(digits = 3)
```


